# Generated by Django 6.0.3 on 2026-04-10 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0020_alter_order_status_add_failed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, default='sendgrid', max_length=32)),
                ('email_type', models.CharField(choices=[('generic', 'Generic'), ('password_reset', 'Password Reset'), ('account_activation', 'Account Activation'), ('order_confirmation', 'Order Confirmation'), ('payment_confirmation', 'Payment Confirmation'), ('order_status', 'Order Status'), ('admin_order_alert', 'Admin Order Alert'), ('test_email', 'Test Email')], db_index=True, default='generic', max_length=64)),
                ('recipient', models.EmailField(db_index=True, max_length=254)),
                ('recipient_domain', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('accepted', 'Accepted'), ('failed', 'Failed'), ('delivered', 'Delivered'), ('deferred', 'Deferred'), ('dropped', 'Dropped'), ('bounced', 'Bounced'), ('blocked', 'Blocked'), ('opened', 'Opened'), ('spam_report', 'Spam Reported')], db_index=True, default='queued', max_length=32)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('sendgrid_message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('sendgrid_response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('send_attempts', models.PositiveIntegerField(default=0)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('retryable', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('provider_response', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_webhook_payload', models.JSONField(blank=True, default=dict)),
                ('last_event_type', models.CharField(blank=True, default='', max_length=64)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('deferred_at', models.DateTimeField(blank=True, null=True)),
                ('dropped_at', models.DateTimeField(blank=True, null=True)),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('spam_reported_at', models.DateTimeField(blank=True, null=True)),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, default='sendgrid', max_length=32)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('sendgrid_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('sendgrid_message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('recipient', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='accounts.emaillog')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status', '-created_at'], name='email_logs_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['email_type', '-created_at'], name='email_logs_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['order', '-created_at'], name='email_logs_order_created_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['user', '-created_at'], name='email_logs_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['recipient', 'status'], name='email_logs_rcpt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='emailwebhookevent',
            index=models.Index(fields=['event_type', '-occurred_at'], name='email_webhook_event_type_idx'),
        ),
        migrations.AddIndex(
            model_name='emailwebhookevent',
            index=models.Index(fields=['email_log', '-occurred_at'], name='email_webhook_email_log_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailwebhookevent',
            constraint=models.UniqueConstraint(condition=models.Q(('sendgrid_event_id', ''), _negated=True), fields=('sendgrid_event_id',), name='email_webhook_events_unique_sendgrid_event_id'),
        ),
    ]
