# Generated by Django 5.2.12 on 2026-04-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_created_at'),
        ('products', '0008_product_products_price_gte_0_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='cart_items_quantity_gt_0'),
        ),
    ]
