# Generated by Django 5.2.12 on 2026-03-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=5),
        ),
    ]
