# Generated by Django 5.2.12 on 2026-03-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_paymentsettings_currency_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('account_sid', models.CharField(blank=True, default='', max_length=255)),
                ('auth_token', models.CharField(blank=True, default='', max_length=255)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=20)),
                ('order_created_template', models.TextField(default='Hello {name}, your order #{order_id} has been placed successfully at SYAFRA. Total: Rs.{total}. Thank you for shopping with us!')),
                ('processing_template', models.TextField(default="Your order #{order_id} is now being processed at SYAFRA. We'll notify you when it's shipped!")),
                ('shipped_template', models.TextField(default='Great news! Your order #{order_id} has been shipped by SYAFRA. It will arrive soon!')),
                ('delivered_template', models.TextField(default='Your order #{order_id} has been delivered by SYAFRA. We hope you love your purchase! Thank you for shopping with us!')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Settings',
                'verbose_name_plural': 'WhatsApp Settings',
            },
        ),
    ]
