# Generated by Django 5.2.12 on 2026-04-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_create_default_whatsapp_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatsAppSettings',
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='payment_methods',
            field=models.JSONField(default=list, help_text='List of enabled payment methods: ["razorpay", "upi", "cod"]'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='upi_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='upi_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='upi_merchant_name',
            field=models.CharField(blank=True, default='SYAFRA', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='upi_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='upi/qr/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='payment_disabled_message',
            field=models.CharField(default='Online payment temporarily unavailable. Please use Cash on Delivery.', max_length=255),
        ),
    ]
