# Generated by Django 5.2.12 on 2026-04-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_add_upi_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When payment was confirmed', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_reduced',
            field=models.BooleanField(default=False, help_text='Whether stock has been reduced for this order'),
        ),
    ]
