# Generated by Django 5.2.12 on 2026-04-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_created_at_alter_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False, help_text='Whether confirmation email has been sent'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_email_sent',
            field=models.BooleanField(default=False, help_text='Whether payment confirmation email has been sent'),
        ),
    ]
