# Generated by Django 5.2.12 on 2026-04-02 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_confirmation_email_sent_and_more'),
        ('products', '0008_product_products_price_gte_0_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', '-created_at'], name='orders_pay_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'payment_status', '-created_at'], name='orders_status_pay_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='order_items_order_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='orders_total_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('stock_reduced', False), ('payment_status', 'paid'), _connector='OR'), name='orders_stock_reduced_requires_paid'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('payment_confirmed_at__isnull', True), ('payment_status', 'paid'), _connector='OR'), name='orders_confirmed_at_requires_paid'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('razorpay_order_id', ''), _negated=True), fields=('razorpay_order_id',), name='orders_unique_razorpay_order_id'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('razorpay_payment_id', ''), _negated=True), fields=('razorpay_payment_id',), name='orders_unique_razorpay_payment_id'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_items_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='order_items_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product', 'size'), name='order_items_unique_order_product_size'),
        ),
    ]
