# Generated by Django 5.2.12 on 2026-04-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_paymentsettings_payment_disabled_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsettings',
            name='payment_disabled_message',
            field=models.CharField(default='Online payment is temporarily unavailable. Please try again later.', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='payment_methods',
            field=models.JSONField(default=list, help_text='List of enabled payment methods: ["razorpay", "upi"]'),
        ),
    ]
