# Generated by Django 5.2.12 on 2026-04-02 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_paymentsettings_payment_disabled_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_email_claimed_at',
            field=models.DateTimeField(blank=True, help_text='When the confirmation email send was claimed by a worker', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_email_claimed_at',
            field=models.DateTimeField(blank=True, help_text='When the payment email send was claimed by a worker', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_retry_reserved_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the current payment retry reservation or retry session was created', null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', 'payment_retry_reserved_at'], name='orders_retry_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('confirmation_email_sent', False), ('confirmation_email_claimed_at__isnull', True), _connector='OR'), name='orders_conf_email_claim_cleared'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('payment_email_sent', False), ('payment_email_claimed_at__isnull', True), _connector='OR'), name='orders_payment_email_claim_cleared'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('payment_retry_reserved_at__isnull', True), ('payment_status', 'pending'), _connector='OR'), name='orders_retry_reservation_pending_only'),
        ),
    ]
