# Generated by Django 6.0.3 on 2026-04-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_confirmation_email_claimed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=20)),
                ('enquiry_whatsapp', models.CharField(blank=True, default='', max_length=20)),
                ('default_message', models.TextField(blank=True, default='Hi, I am interested in your products. Please share more details.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Setting',
                'verbose_name_plural': 'WhatsApp Settings',
            },
        ),
    ]
