# Generated by Django 5.2.12 on 2026-04-07 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_whatsappsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('razorpay', 'Razorpay'), ('upi', 'UPI')], db_index=True, default='razorpay', max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('authorized', 'Authorized'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('receipt', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, default='', max_length=255)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='admin_notification_claimed_at',
            field=models.DateTimeField(blank=True, help_text='When the admin notification send was claimed by a worker', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_notification_sent',
            field=models.BooleanField(default=False, help_text='Whether the admin new-order notification email has been sent'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('admin_notification_sent', False), ('admin_notification_claimed_at__isnull', True), _connector='OR'), name='orders_admin_email_claim_cleared'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', '-created_at'], name='payments_order_created_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'status', '-created_at'], name='payments_provider_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payments_amount_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('razorpay_order_id', ''), _negated=True), fields=('razorpay_order_id',), name='payments_unique_razorpay_order_id'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('razorpay_payment_id', ''), _negated=True), fields=('razorpay_payment_id',), name='payments_unique_razorpay_payment_id'),
        ),
    ]
