# Generated by Django 5.2.12 on 2026-04-07 14:12

from django.db import migrations, models


def remap_legacy_order_statuses(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(status='confirmed').update(status='paid')
    Order.objects.filter(status='processing').update(status='packed')


def restore_legacy_order_statuses(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(status='paid', payment_status='paid').update(status='confirmed')
    Order.objects.filter(status='packed').update(status='processing')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_payment_order_admin_notification_claimed_at_and_more'),
    ]

    operations = [
        migrations.RunPython(remap_legacy_order_statuses, restore_legacy_order_statuses),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
