# Generated by Django 6.0.3 on 2026-07-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsettings',
            name='account_sid',
            field=models.CharField(blank=True, default='', help_text='Twilio Account SID', max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='auth_token',
            field=models.CharField(blank=True, default='', help_text='Twilio Auth Token', max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='delivered_template',
            field=models.TextField(blank=True, default='', help_text='WhatsApp template for delivered orders. Placeholders: {name}, {order_id}, {total}'),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='order_created_template',
            field=models.TextField(blank=True, default='', help_text='WhatsApp template for new orders. Placeholders: {name}, {order_id}, {total}'),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='processing_template',
            field=models.TextField(blank=True, default='', help_text='WhatsApp template for processing orders. Placeholders: {name}, {order_id}, {total}'),
        ),
        migrations.AddField(
            model_name='whatsappsettings',
            name='shipped_template',
            field=models.TextField(blank=True, default='', help_text='WhatsApp template for shipped orders. Placeholders: {name}, {order_id}, {total}'),
        ),
    ]
