# Generated by Django 5.2.12 on 2026-04-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_created_at_alter_product_is_featured'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='products_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='products_stock_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='productsize',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='product_sizes_stock_gte_0'),
        ),
    ]
