# Generated by Django 6.0.3 on 2026-04-09 15:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_products_price_gte_0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
