# Generated by Django 5.0.14 on 2026-07-03 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_instagrampost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('announcement_bar', 'Announcement Bar'), ('hero_slider', 'Hero Slider'), ('trust_bar', 'Trust Bar'), ('shop_by_category', 'Shop By Category'), ('product_collection', 'Product Collection'), ('promotional_banner', 'Promotional Banner'), ('customer_reviews', 'Customer Reviews'), ('instagram_feed', 'Instagram Feed'), ('newsletter', 'Newsletter'), ('footer', 'Footer')], max_length=50, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=300)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('device_settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Section',
                'verbose_name_plural': 'Homepage Sections',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(default='homepage', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='SYAFRA', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Fashion-Forward Vintage Streetwear', max_length=200)),
                ('primary_color', models.CharField(default='#000000', help_text='Primary brand color', max_length=7)),
                ('secondary_color', models.CharField(default='#FFFFFF', help_text='Secondary brand color', max_length=7)),
                ('accent_color', models.CharField(default='#E8DCC4', help_text='Accent/highlight color', max_length=7)),
                ('logo', models.ImageField(blank=True, upload_to='theme/')),
                ('favicon', models.ImageField(blank=True, upload_to='theme/')),
                ('enable_loader', models.BooleanField(default=False)),
                ('loader_type', models.CharField(choices=[('spinner', 'Spinner'), ('dots', 'Dots'), ('pulse', 'Pulse'), ('bar', 'Bar')], default='spinner', max_length=20)),
                ('loader_color', models.CharField(default='#000000', max_length=7)),
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('business_address', models.TextField(blank=True, default='')),
                ('business_hours', models.CharField(default='Mon-Sat: 10AM - 8PM', max_length=200)),
                ('whatsapp_number', models.CharField(default='919037626684', max_length=20)),
                ('whatsapp_default_message', models.CharField(default='Hi, I am interested in your products. Please share more details.', max_length=500)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.CharField(default='We are currently undergoing maintenance. Please check back later.', max_length=500)),
                ('seo_title', models.CharField(default='SYAFRA - Fashion-Forward Vintage Streetwear', max_length=70)),
                ('seo_description', models.CharField(default='Curated vintage jackets and streetwear. Authentic pieces, modern style.', max_length=160)),
                ('seo_keywords', models.CharField(default='vintage jackets, streetwear, fashion, thrift', max_length=255)),
                ('og_image', models.ImageField(blank=True, upload_to='theme/')),
                ('google_search_console_verification', models.CharField(blank=True, default='', max_length=100)),
                ('google_analytics_id', models.CharField(blank=True, default='', max_length=50)),
                ('meta_pixel_id', models.CharField(blank=True, default='', max_length=50)),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('tiktok_url', models.URLField(blank=True, default='')),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('pinterest_url', models.URLField(blank=True, default='')),
                ('threads_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('copyright_text', models.CharField(default='2026 SYAFRA. All rights reserved.', max_length=200)),
            ],
            options={
                'verbose_name': 'Website Settings',
                'verbose_name_plural': 'Website Settings',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('button_text', models.CharField(default='SHOP NOW', max_length=50)),
                ('button_url', models.CharField(default='/shop/', max_length=500)),
                ('desktop_image', models.ImageField(blank=True, upload_to='homepage/hero/desktop/')),
                ('mobile_image', models.ImageField(blank=True, upload_to='homepage/hero/mobile/')),
                ('overlay_opacity', models.PositiveIntegerField(default=60, help_text='Overlay darkness 0-100')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='products.homepagesection')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_heading', models.CharField(help_text='Group label (e.g. SHOP, HELP)', max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('is_external', models.BooleanField(default=False, help_text='Opens in new tab')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='products.homepagesection')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, related_name='collections', to='products.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Required for Product Collection sections.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='products.productcollection'),
        ),
        migrations.CreateModel(
            name='TrustBarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_svg', models.TextField(blank=True, default='', help_text='SVG path data for icon')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_items', to='products.homepagesection')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ShopByCategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, default='', max_length=100)),
                ('label', models.CharField(default='EXPLORE', max_length=50)),
                ('desktop_image', models.ImageField(blank=True, upload_to='homepage/categories/desktop/')),
                ('mobile_image', models.ImageField(blank=True, upload_to='homepage/categories/mobile/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_items', to='products.homepagesection')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('section', 'category')},
            },
        ),
    ]
