# Generated by Django 5.2.15 on 2026-07-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_homepagesection_newslettersubscriber_themesettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('announcement_bar', 'Announcement Bar'), ('hero_slider', 'Hero Slider'), ('trust_bar', 'Trust Bar'), ('shop_by_category', 'Shop By Category'), ('product_collection', 'Product Collection'), ('womens_tops', "Women's Tops"), ('trending_now', 'Trending Now'), ('best_sellers', 'Best Sellers'), ('promotional_banner', 'Promotional Banner'), ('customer_reviews', 'Customer Reviews'), ('instagram_feed', 'Instagram Feed'), ('newsletter', 'Newsletter'), ('footer', 'Footer')], max_length=50, unique=True),
        ),
    ]
