# Generated by Django 5.2.15 on 2026-07-05 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_add_collection_section_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='image_position_x',
            field=models.PositiveSmallIntegerField(default=60, help_text='Image horizontal focal point: 0=left, 50=center, 100=right', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image_position_y',
            field=models.PositiveSmallIntegerField(default=50, help_text='Image vertical focal point: 0=top, 50=center, 100=bottom', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='seo_description',
            field=models.CharField(default='Discover curated fashion, distinctive silhouettes, and modern essentials at SYAFRA. Explore new arrivals and collections designed for everyday expression.', max_length=160),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='seo_keywords',
            field=models.CharField(default='curated fashion, modern style, new arrivals, streetwear, designer pieces, fashion brand', max_length=255),
        ),
    ]
