# Generated by Django 6.0.3 on 2026-07-08 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_heroslide_image_position_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='overline',
            field=models.CharField(blank=True, default='', help_text='Small label above the title (e.g. "NEW ARRIVALS", "THE EDIT")', max_length=100),
        ),
        migrations.CreateModel(
            name='PromotionalBannerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desktop_image', models.ImageField(blank=True, upload_to='homepage/promo/')),
                ('mobile_image', models.ImageField(blank=True, upload_to='homepage/promo/')),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promo_config', to='products.homepagesection')),
            ],
            options={
                'verbose_name': 'Promotional Banner Image',
                'verbose_name_plural': 'Promotional Banner Images',
            },
        ),
    ]
