# Generated by Django 5.2.15 on 2026-07-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_instagram_publishing_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='websitesettings',
            name='instagram_auto_publish',
        ),
        migrations.DeleteModel(
            name='InstagramPost',
        ),
    ]
