# Generated by Django 6.0.3 on 2026-07-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this product has been viewed'),
        ),
    ]
