# Generated by Django 6.0.3 on 2026-07-24 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        ('products', '0017_add_product_views_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='instagramfeeditem',
            options={'ordering': ['display_order'], 'verbose_name': 'Instagram Feed Item', 'verbose_name_plural': 'Instagram Feed Items'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='instagramfeeditem',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='cms.brand'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('announcement_bar', 'Announcement Bar'), ('hero_slider', 'Hero Slider'), ('trust_bar', 'Trust Bar'), ('shop_by_category', 'Shop By Category'), ('product_collection', 'Product Collection'), ('womens_tops', "Women's Tops"), ('trending_now', 'Trending Now'), ('best_sellers', 'Best Sellers'), ('promotional_banner', 'Promotional Banner'), ('customer_reviews', 'Customer Reviews'), ('instagram_feed', 'Instagram Feed'), ('newsletter', 'Newsletter'), ('footer', 'Footer')], max_length=50),
        ),
    ]
