# Generated by Django 6.0.3 on 2026-07-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='anchor_id',
            field=models.CharField(blank=True, default='', help_text='Section anchor ID for linking', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='animation',
            field=models.CharField(blank=True, choices=[('', 'None'), ('fade-in', 'Fade In'), ('fade-up', 'Fade Up'), ('fade-down', 'Fade Down'), ('slide-left', 'Slide Left'), ('slide-right', 'Slide Right'), ('zoom-in', 'Zoom In'), ('zoom-out', 'Zoom Out'), ('flip', 'Flip')], default='', help_text='Scroll animation', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='bg_color',
            field=models.CharField(blank=True, default='', help_text='Section background color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='bg_image',
            field=models.ImageField(blank=True, help_text='Section background image', upload_to='sections/bg/'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='border_radius',
            field=models.CharField(blank=True, choices=[('rounded-none', 'None'), ('rounded-sm', 'Small'), ('rounded', 'Medium'), ('rounded-lg', 'Large'), ('rounded-xl', 'Extra Large'), ('rounded-full', 'Full')], default='', help_text='Section border radius', max_length=20),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='container_width',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('max-w-5xl', 'max-w-5xl'), ('max-w-6xl', 'max-w-6xl'), ('max-w-7xl', 'max-w-7xl'), ('max-w-full', 'max-w-full')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='custom_css_class',
            field=models.CharField(blank=True, default='', help_text='Custom CSS class(es) for the section', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='full_width',
            field=models.BooleanField(default=False, help_text='Stretch to full viewport width'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='hide_on_desktop',
            field=models.BooleanField(default=False, help_text='Hide on desktop devices'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='hide_on_mobile',
            field=models.BooleanField(default=False, help_text='Hide on mobile devices'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='hide_on_tablet',
            field=models.BooleanField(default=False, help_text='Hide on tablet devices'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='margin',
            field=models.CharField(blank=True, choices=[('m-0', 'None'), ('mt-4', 'Top Small'), ('mt-8', 'Top Medium'), ('mt-16', 'Top Large'), ('mb-4', 'Bottom Small'), ('mb-8', 'Bottom Medium'), ('mb-16', 'Bottom Large'), ('my-4', 'Both Small'), ('my-8', 'Both Medium'), ('my-16', 'Both Large')], default='', help_text='Section margin', max_length=20),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='padding_bottom',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('py-8', 'py-8'), ('py-12', 'py-12'), ('py-16', 'py-16'), ('py-20', 'py-20'), ('py-24', 'py-24'), ('py-32', 'py-32')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='padding_top',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('py-8', 'py-8'), ('py-12', 'py-12'), ('py-16', 'py-16'), ('py-20', 'py-20'), ('py-24', 'py-24'), ('py-32', 'py-32')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='publish_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Schedule publish date', null=True),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='unpublish_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Schedule unpublish date', null=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='background_color',
            field=models.CharField(default='#ffffff', help_text='Page background', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='blog_layout',
            field=models.CharField(choices=[('list', 'List'), ('grid', 'Grid')], default='grid', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='body_font',
            field=models.CharField(default='Inter', help_text='Body font family', max_length=100),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='body_font_weight',
            field=models.CharField(default='400', help_text='Body font weight', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='border_color',
            field=models.CharField(default='#e5e7eb', help_text='Border color', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='button_animations_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='card_animations_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='card_color',
            field=models.CharField(default='#ffffff', help_text='Card background', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='cart_notes_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='category_grid_layout',
            field=models.CharField(choices=[('2cols', '2 Columns'), ('3cols', '3 Columns'), ('4cols', '4 Columns'), ('5cols', '5 Columns')], default='3cols', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='checkout_css',
            field=models.TextField(blank=True, default='', help_text='Custom CSS for checkout'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='compare_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='container_width',
            field=models.CharField(default='max-w-7xl', help_text='Main container width class', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='cross_sell_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='custom_js',
            field=models.TextField(blank=True, default='', help_text='Custom JavaScript'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='danger_color',
            field=models.CharField(default='#ef4444', help_text='Danger/error color', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='default_sorting',
            field=models.CharField(choices=[('newest', 'Newest First'), ('oldest', 'Oldest First'), ('price_low', 'Price: Low to High'), ('price_high', 'Price: High to Low'), ('name_az', 'Name: A-Z'), ('name_za', 'Name: Z-A')], default='newest', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='delivery_info_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='font_size_scale',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='Font size scale multiplier (0.8 - 1.5)', max_digits=3),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_columns',
            field=models.PositiveIntegerField(default=4, help_text='Number of footer columns'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_copyright',
            field=models.CharField(blank=True, default='', help_text='Copyright text', max_length=200),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_css',
            field=models.TextField(blank=True, default='', help_text='Custom CSS for footer'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='footer_newsletter_enabled',
            field=models.BooleanField(default=True, help_text='Show newsletter signup in footer'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='gallery_layout',
            field=models.CharField(choices=[('single', 'Single Image'), ('grid', 'Grid'), ('carousel', 'Carousel'), ('sticky', 'Sticky Gallery')], default='carousel', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='global_css',
            field=models.TextField(blank=True, default='', help_text='Custom CSS applied globally'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='header_css',
            field=models.TextField(blank=True, default='', help_text='Custom CSS for header'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='header_style',
            field=models.CharField(choices=[('classic', 'Classic'), ('centered', 'Centered'), ('minimal', 'Minimal'), ('hamburger', 'Hamburger Only')], default='classic', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='heading_font',
            field=models.CharField(default='Cormorant Garamond', help_text='Heading font family', max_length=100),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='heading_font_weight',
            field=models.CharField(default='600', help_text='Heading font weight (e.g. 400, 500, 600, 700)', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='homepage_css',
            field=models.TextField(blank=True, default='', help_text='Custom CSS for homepage'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='hover_effects_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='image_zoom_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='infinite_scroll_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='info_color',
            field=models.CharField(default='#3b82f6', help_text='Info color', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='layout_style',
            field=models.CharField(choices=[('boxed', 'Boxed'), ('full_width', 'Full Width')], default='full_width', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='letter_spacing',
            field=models.CharField(default='normal', help_text='Global letter spacing (e.g. normal, 0.5px, 1px)', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='line_height',
            field=models.DecimalField(decimal_places=1, default=1.6, help_text='Global line height', max_digits=3),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='loading_animations_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='mega_menu_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='mini_cart_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='mobile_menu_style',
            field=models.CharField(blank=True, default='slide', help_text='Mobile menu animation style', max_length=50),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='muted_text_color',
            field=models.CharField(default='#6b7280', help_text='Muted/secondary text', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='page_transitions_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='pagination_style',
            field=models.CharField(choices=[('numbers', 'Page Numbers'), ('prev_next', 'Prev/Next'), ('load_more', 'Load More')], default='numbers', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='payment_icons_enabled',
            field=models.BooleanField(default=True, help_text='Show payment method icons in footer'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='preview_mode',
            field=models.BooleanField(default=False, help_text='Enable live preview mode'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='primary_btn_bg',
            field=models.CharField(default='#000000', help_text='Primary button background', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='primary_btn_border_radius',
            field=models.CharField(choices=[('rounded-none', 'None'), ('rounded-sm', 'Small'), ('rounded', 'Medium'), ('rounded-lg', 'Large'), ('rounded-full', 'Full')], default='rounded', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='primary_btn_hover_animation',
            field=models.CharField(blank=True, default='', help_text='Hover animation effect', max_length=50),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='primary_btn_shadow',
            field=models.BooleanField(default=False, help_text='Enable shadow on primary button'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='primary_btn_text',
            field=models.CharField(default='#ffffff', help_text='Primary button text color', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='product_css',
            field=models.TextField(blank=True, default='', help_text='Custom CSS for product pages'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='product_grid_layout',
            field=models.CharField(choices=[('2cols', '2 Columns'), ('3cols', '3 Columns'), ('4cols', '4 Columns'), ('5cols', '5 Columns')], default='4cols', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='products_per_page',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='quick_view_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='recently_viewed_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='recently_viewed_products_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='related_products_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='scroll_animations_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='secondary_btn_bg',
            field=models.CharField(default='#ffffff', help_text='Secondary button background', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='secondary_btn_border_radius',
            field=models.CharField(choices=[('rounded-none', 'None'), ('rounded-sm', 'Small'), ('rounded', 'Medium'), ('rounded-lg', 'Large'), ('rounded-full', 'Full')], default='rounded', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='secondary_btn_hover_animation',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='secondary_btn_shadow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='secondary_btn_text',
            field=models.CharField(default='#000000', help_text='Secondary button text color', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='shipping_progress_bar_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='sidebar_width',
            field=models.CharField(default='w-72', help_text='Sidebar width class', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='size_chart_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='slide_cart_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='social_links_enabled',
            field=models.BooleanField(default=True, help_text='Show social media links in footer'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='spacing_scale',
            field=models.CharField(default='default', help_text='Global spacing scale', max_length=20),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='sticky_buy_box_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='sticky_gallery_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='sticky_header',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='success_color',
            field=models.CharField(default='#10b981', help_text='Success/confirmation color', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='surface_color',
            field=models.CharField(default='#f9fafb', help_text='Surface background', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='text_color',
            field=models.CharField(default='#111827', help_text='Body text color', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='transparent_header',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='trust_badges_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='upsell_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='warning_color',
            field=models.CharField(default='#f59e0b', help_text='Warning color', max_length=7),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='wishlist_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('announcement_bar', 'Announcement Bar'), ('hero_slider', 'Hero Slider'), ('hero_banner', 'Hero Banner'), ('shop_by_category', 'Shop By Category'), ('featured_products', 'Featured Products'), ('new_arrivals', 'New Arrivals'), ('trending_products', 'Trending Products'), ('best_sellers', 'Best Sellers'), ('collections', 'Collections'), ('brands', 'Brands'), ('womens_tops', "Women's Tops"), ('jackets', 'Jackets'), ('lookbook', 'Lookbook'), ('customer_reviews', 'Customer Reviews'), ('instagram_feed', 'Instagram Feed'), ('newsletter', 'Newsletter'), ('promotional_banner', 'Promotional Banner'), ('faq_section', 'FAQ'), ('custom_html', 'Custom HTML'), ('custom_template', 'Custom Template'), ('video_banner', 'Video Banner'), ('image_gallery', 'Image Gallery'), ('countdown_banner', 'Countdown Banner'), ('recently_viewed', 'Recently Viewed'), ('recommended_products', 'Recommended Products'), ('flash_sale', 'Flash Sale'), ('trust_bar', 'Trust Bar'), ('product_collection', 'Product Collection'), ('footer', 'Footer')], max_length=50),
        ),
    ]
