# Generated by Django 6.0.3 on 2026-07-25 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_homepagesection_anchor_id_homepagesection_animation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
