# Generated by Django 6.0.3 on 2026-07-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of the original uploaded image', max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='image_norm_version',
            field=models.PositiveIntegerField(default=0, help_text='Normalization algorithm version used'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of the original uploaded image', max_length=64),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_norm_version',
            field=models.PositiveIntegerField(default=0, help_text='Normalization algorithm version used'),
        ),
    ]
