# Generated by Django 6.0.3 on 2026-07-30 05:27

from django.db import migrations, models


def migrate_trending_products_to_trending_now(apps, schema_editor):
    HomepageSection = apps.get_model('products', 'HomepageSection')
    HomepageSection.objects.filter(section_type='trending_products').update(section_type='trending_now')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_add_image_normalization_tracking'),
    ]

    operations = [
        migrations.RunPython(migrate_trending_products_to_trending_now, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('announcement_bar', 'Announcement Bar'), ('hero_slider', 'Hero Slider'), ('hero_banner', 'Hero Banner'), ('shop_by_category', 'Shop By Category'), ('featured_products', 'Featured Products'), ('new_arrivals', 'New Arrivals'), ('trending_now', 'Trending Now'), ('best_sellers', 'Best Sellers'), ('collections', 'Collections'), ('brands', 'Brands'), ('womens_tops', "Women's Tops"), ('jackets', 'Jackets'), ('lookbook', 'Lookbook'), ('customer_reviews', 'Customer Reviews'), ('instagram_feed', 'Instagram Feed'), ('newsletter', 'Newsletter'), ('promotional_banner', 'Promotional Banner'), ('faq_section', 'FAQ'), ('custom_html', 'Custom HTML'), ('custom_template', 'Custom Template'), ('video_banner', 'Video Banner'), ('image_gallery', 'Image Gallery'), ('countdown_banner', 'Countdown Banner'), ('recently_viewed', 'Recently Viewed'), ('recommended_products', 'Recommended Products'), ('flash_sale', 'Flash Sale'), ('trust_bar', 'Trust Bar'), ('product_collection', 'Product Collection'), ('footer', 'Footer')], max_length=50),
        ),
    ]
