from django.core.management.base import BaseCommand
from products.models import Category, Product


class Command(BaseCommand):
    help = 'Adds sample products to the database'

    def handle(self, *args, **options):
        # Create categories
        categories_data = [
            {'name': 'Leather Jackets', 'slug': 'leather-jackets', 'description': 'Premium leather jackets'},
            {'name': 'Denim Jackets', 'slug': 'denim-jackets', 'description': 'Vintage denim jackets'},
            {'name': 'Bomber Jackets', 'slug': 'bomber-jackets', 'description': 'Classic bomber jackets'},
            {'name': 'Varsity Jackets', 'slug': 'varsity-jackets', 'description': 'Retro varsity jackets'},
            {'name': 'Parkas', 'slug': 'parkas', 'description': 'Winter parkas and coats'},
            {'name': 'Blazers', 'slug': 'blazers', 'description': 'Smart casual blazers'},
        ]
        
        categories = {}
        for cat_data in categories_data:
            cat, created = Category.objects.get_or_create(
                slug=cat_data['slug'],
                defaults=cat_data
            )
            categories[cat_data['slug']] = cat
            if created:
                self.stdout.write(f'Created category: {cat.name}')
        
        # Create products
        products_data = [
            # Leather Jackets (6 products)
            {
                'name': 'Vintage Leather Biker Jacket',
                'brand': 'Schott',
                'category': categories['leather-jackets'],
                'size': 'L',
                'condition': 'used',
                'price': 299.99,
                'description': 'Classic 1980s Schott leather biker jacket. Rich patina, all original hardware.',
                'stock': 3,
                'is_featured': True,
            },
            {
                'name': 'Distressed Moto Leather',
                'brand': 'Chrome Hearts',
                'category': categories['leather-jackets'],
                'size': 'M',
                'condition': 'refurbished',
                'price': 449.99,
                'description': 'Heavily distressed moto-style leather jacket with silver hardware.',
                'stock': 2,
                'is_featured': True,
            },
            {
                'name': 'Cropped Leather Bomber',
                'brand': 'Saint Laurent',
                'category': categories['leather-jackets'],
                'size': 'S',
                'condition': 'used',
                'price': 599.99,
                'description': 'Elegant cropped leather bomber. Minor wear adds character.',
                'stock': 1,
                'is_featured': True,
            },
            {
                'name': 'Racer Leather Jacket',
                'brand': 'Lewis Leathers',
                'category': categories['leather-jackets'],
                'size': 'XL',
                'condition': 'new',
                'price': 349.99,
                'description': 'Classic British racer style leather jacket. Smooth finish.',
                'stock': 4,
                'is_featured': True,
            },
            {
                'name': 'Aviator Sheepskin Coat',
                'brand': 'Cockpit USA',
                'category': categories['leather-jackets'],
                'size': 'L',
                'condition': 'used',
                'price': 499.99,
                'description': 'Authentic aviator sheepskin coat. Incredibly soft and warm.',
                'stock': 2,
                'is_featured': True,
            },
            {
                'name': 'Studded Punk Leather',
                'brand': 'Dr. Martens',
                'category': categories['leather-jackets'],
                'size': 'M',
                'condition': 'new',
                'price': 279.99,
                'description': 'Punk-inspired leather jacket with studded details.',
                'stock': 5,
                'is_featured': False,
            },
            
            # Denim Jackets (6 products)
            {
                'name': 'Vintage Levi\'s Trucker',
                'brand': 'Levi\'s',
                'category': categories['denim-jackets'],
                'size': 'M',
                'condition': 'used',
                'price': 149.99,
                'description': 'Authentic 1970s Levi\'s trucker jacket. Beautiful fade and wear patterns.',
                'stock': 4,
                'is_featured': True,
            },
            {
                'name': 'Raw Denim Type III',
                'brand': 'Iron Heart',
                'category': categories['denim-jackets'],
                'size': 'L',
                'condition': 'new',
                'price': 199.99,
                'description': 'Heavyweight 21oz raw denim Type III jacket. Unwashed, pure indigo.',
                'stock': 5,
                'is_featured': True,
            },
            {
                'name': 'Tie-Dye Denim Jacket',
                'brand': 'True Religion',
                'category': categories['denim-jackets'],
                'size': 'XL',
                'condition': 'used',
                'price': 89.99,
                'description': 'Unique hand-dyed denim jacket. One of a kind.',
                'stock': 2,
                'is_featured': True,
            },
            {
                'name': 'Embroidered Denim',
                'brand': 'Gucci',
                'category': categories['denim-jackets'],
                'size': 'S',
                'condition': 'new',
                'price': 399.99,
                'description': 'Floral embroidered denim jacket. Statement piece.',
                'stock': 3,
                'is_featured': True,
            },
            {
                'name': 'Sherpa Lined Trucker',
                'brand': 'Wrangler',
                'category': categories['denim-jackets'],
                'size': 'L',
                'condition': 'used',
                'price': 119.99,
                'description': 'Cozy sherpa-lined trucker. Perfect for cold weather.',
                'stock': 6,
                'is_featured': True,
            },
            {
                'name': 'Painted Denim Jacket',
                'brand': 'Supreme',
                'category': categories['denim-jackets'],
                'size': 'M',
                'condition': 'used',
                'price': 249.99,
                'description': 'Artistically painted denim. Custom artwork makes each unique.',
                'stock': 1,
                'is_featured': False,
            },
            
            # Bomber Jackets (6 products)
            {
                'name': 'MA-1 Flight Bomber',
                'brand': 'Alpha Industries',
                'category': categories['bomber-jackets'],
                'size': 'M',
                'condition': 'used',
                'price': 179.99,
                'description': 'Classic MA-1 nylon bomber. Military surplus, authentic olive drab.',
                'stock': 6,
                'is_featured': True,
            },
            {
                'name': 'Satin Baseball Bomber',
                'brand': 'Addict',
                'category': categories['bomber-jackets'],
                'size': 'L',
                'condition': 'new',
                'price': 229.99,
                'description': 'Premium satin bomber with embroidered baseball design.',
                'stock': 3,
                'is_featured': True,
            },
            {
                'name': 'Puffer Down Bomber',
                'brand': 'Moncler',
                'category': categories['bomber-jackets'],
                'size': 'M',
                'condition': 'used',
                'price': 399.99,
                'description': 'Lightweight down-filled bomber. Perfect for layering.',
                'stock': 2,
                'is_featured': True,
            },
            {
                'name': 'Varsity Satin Bomber',
                'brand': 'Starter',
                'category': categories['bomber-jackets'],
                'size': 'XL',
                'condition': 'new',
                'price': 189.99,
                'description': 'Retro varsity-style satin bomber with team colors.',
                'stock': 4,
                'is_featured': True,
            },
            {
                'name': 'Suede Bomber Jacket',
                'brand': 'Calvin Klein',
                'category': categories['bomber-jackets'],
                'size': 'L',
                'condition': 'used',
                'price': 299.99,
                'description': 'Luxurious suede bomber. Soft texture, classic silhouette.',
                'stock': 3,
                'is_featured': True,
            },
            {
                'name': 'N-2B Tactical Bomber',
                'brand': 'Alpha Industries',
                'category': categories['bomber-jackets'],
                'size': 'L',
                'condition': 'new',
                'price': 249.99,
                'description': 'Extended tactical bomber. Extra warmth with hooded design.',
                'stock': 5,
                'is_featured': False,
            },
            
            # Varsity Jackets (6 products)
            {
                'name': 'Wool Letterman Varsity',
                'brand': 'Wilson\'s Leather',
                'category': categories['varsity-jackets'],
                'size': 'L',
                'condition': 'used',
                'price': 189.99,
                'description': 'Classic wool and leather varsity jacket. Embroidered letter.',
                'stock': 3,
                'is_featured': True,
            },
            {
                'name': 'Retro Stripes Varsity',
                'brand': 'Vans',
                'category': categories['varsity-jackets'],
                'size': 'XL',
                'condition': 'new',
                'price': 159.99,
                'description': 'Modern take on the varsity jacket with bold stripe detail.',
                'stock': 4,
                'is_featured': True,
            },
            {
                'name': 'Chenille Patch Varsity',
                'brand': 'Obey',
                'category': categories['varsity-jackets'],
                'size': 'M',
                'condition': 'used',
                'price': 129.99,
                'description': 'Statement varsity with large chenille patches.',
                'stock': 2,
                'is_featured': True,
            },
            {
                'name': 'Satin Letterman Jacket',
                'brand': 'Tommy Hilfiger',
                'category': categories['varsity-jackets'],
                'size': 'L',
                'condition': 'new',
                'price': 199.99,
                'description': 'All-satin letterman with felt appliqués.',
                'stock': 5,
                'is_featured': True,
            },
            {
                'name': 'Pinstripe Varsity',
                'brand': 'Ralph Lauren',
                'category': categories['varsity-jackets'],
                'size': 'M',
                'condition': 'used',
                'price': 249.99,
                'description': 'Sophisticated pinstripe varsity. Business casual meets streetwear.',
                'stock': 2,
                'is_featured': True,
            },
            {
                'name': 'Distressed Vintage Varsity',
                'brand': 'Unbranded',
                'category': categories['varsity-jackets'],
                'size': 'XL',
                'condition': 'used',
                'price': 179.99,
                'description': 'Perfectly worn-in vintage varsity. Soft wool, broken-in leather.',
                'stock': 1,
                'is_featured': False,
            },
            
            # Parkas (4 products)
            {
                'name': 'M65 Field Jacket',
                'brand': 'Alpha Industries',
                'category': categories['parkas'],
                'size': 'L',
                'condition': 'used',
                'price': 219.99,
                'description': 'Iconic M65 field jacket. Olive drab, detachable liner.',
                'stock': 4,
                'is_featured': True,
            },
            {
                'name': 'Canada Goose Parka',
                'brand': 'Canada Goose',
                'category': categories['parkas'],
                'size': 'M',
                'condition': 'new',
                'price': 799.99,
                'description': 'Premium down parka. Extreme warmth rating.',
                'stock': 2,
                'is_featured': True,
            },
            {
                'name': 'Quilted Liner Parka',
                'brand': 'Carhartt',
                'category': categories['parkas'],
                'size': 'XL',
                'condition': 'used',
                'price': 149.99,
                'description': 'Workwear parka with quilted lining. Durable duck canvas.',
                'stock': 5,
                'is_featured': True,
            },
            {
                'name': 'Tactical Anorak',
                'brand': 'Arc\'teryx',
                'category': categories['parkas'],
                'size': 'L',
                'condition': 'new',
                'price': 449.99,
                'description': 'Technical anorak. Waterproof, breathable shell.',
                'stock': 3,
                'is_featured': False,
            },
            
            # Blazers (4 products)
            {
                'name': 'Velvet Blazer',
                'brand': 'Hugo Boss',
                'category': categories['blazers'],
                'size': 'M',
                'condition': 'used',
                'price': 199.99,
                'description': 'Rich burgundy velvet blazer. Evening wear ready.',
                'stock': 2,
                'is_featured': True,
            },
            {
                'name': 'Tweed Sport Coat',
                'brand': 'Ralph Lauren',
                'category': categories['blazers'],
                'size': 'L',
                'condition': 'new',
                'price': 279.99,
                'description': 'Classic Harris tweed sport coat. Timeless pattern.',
                'stock': 3,
                'is_featured': True,
            },
            {
                'name': 'Leather Blazer',
                'brand': 'Zegna',
                'category': categories['blazers'],
                'size': 'M',
                'condition': 'used',
                'price': 399.99,
                'description': 'Premium leather blazer. Soft nappa leather.',
                'stock': 1,
                'is_featured': True,
            },
            {
                'name': 'Denim Blazer',
                'brand': 'Acne Studios',
                'category': categories['blazers'],
                'size': 'L',
                'condition': 'new',
                'price': 329.99,
                'description': 'Casual denim blazer. Relaxed fit, modern style.',
                'stock': 4,
                'is_featured': False,
            },
        ]
        
        for prod_data in products_data:
            prod, created = Product.objects.get_or_create(
                name=prod_data['name'],
                defaults=prod_data
            )
            if created:
                self.stdout.write(f'Created product: {prod.name}')
        
        self.stdout.write(self.style.SUCCESS(f'Sample products added successfully! Total: {len(products_data)} products'))
